server:
  port: 8080
  virtual-threads:
    enabled: true
  error:
    include-stacktrace: never
    include-binding-errors: never



clients:
  task:
    url: http://localhost:8081
  activity:
    url: http://localhost:8082

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: gateway
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "com.viniss.todo.common.events,com.viniss.todo.common.dto"
  security:
    oauth2:
      resourceserver:
        jwt:
          # Para Keycloak
          issuer-uri: "${JWT_ISSUER_URI:http://localhost:8080/auth/realms/todo-realm}"

          # Para Auth0 ou similar (alternativa)
          # issuer-uri: "${JWT_ISSUER_URI:https://your-tenant.auth0.com/}"

          # Para validação customizada (se necessário)
          # jwk-set-uri: "${JWT_JWK_SET_URI:http://localhost:8080/auth/realms/todo-realm/protocol/openid_connect/certs}"

  cloud:
    openfeign:
      client:
        # (opcional) permitir refresh dinâmico desses timeouts via /actuator/refresh
        refresh-enabled: true
        config:
          task:
            connectTimeout: 1000    # 1s
            readTimeout: 1500       # 1.5s
            loggerLevel: basic


resilience4j:
  circuitbreaker:
    instances:
      task:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3




  retry:
    instances:
      task:
        maxAttempts: 3
        waitDuration: 200ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - feign.RetryableException
          - java.io.IOException

  timelimiter:
    instances:
      task:
        timeoutDuration: 2s


# Configurações de segurança para application.yml do api-gateway
app:
  websocket:
    allowed-origins:
      - "http://localhost:3000"
  cors:
    allowed-origins:
      - "http://localhost:3000"


