server:
  port: 8080
  virtual-threads:
    enabled: true

clients:
  task:
    url: http://localhost:8081
  activity:
    url: http://localhost:8082

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: gateway
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
