name: CI

on:
  push:
    branches: ["main", "develop", "release/**"]
    paths-ignore: ["**/*.md", "docs/**"]
  pull_request:
    branches: ["main", "develop"]

permissions:
  contents: read
  checks: write

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Set up Maven
        uses: s4u/setup-maven-action@v1
        with:
          maven-version: '3.9.8'

      - name: Build and test (Maven verify)
        run: mvn -B -ntp -Dstyle.color=always verify

      - name: Publish JUnit to PR
        if: always() && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false)
        uses: dorny/test-reporter@v2
        with:
          name: Testes Maven
          path: "**/target/surefire-reports/*.xml"
          reporter: java-junit

      - name: Upload test reports (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: |
            **/target/surefire-reports/**
            **/target/failsafe-reports/**
          retention-days: 7

      - name: Upload JAR (opcional)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: "**/target/*.jar"
          retention-days: 7
