name: Lint PR Title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]

permissions:
  pull-requests: read

jobs:
  semantic-pr:
    name: Validate PR title (Conventional Commits)
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            build
            chore
            ci
            docs
            feat
            fix
            perf
            refactor
            revert
            style
            test
          requireScope: false
          subjectPattern: ".+"
          subjectPatternError: "O assunto do título não pode ser vazio."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
