name: Release Image

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

concurrency:
  group: release-image-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  jib:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [activity-service, task-service, api-gateway]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Set up Maven
        uses: s4u/setup-maven-action@v1
        with:
          maven-version: '3.9.8'

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase repo for GHCR
        run: |
          echo "GH_REPOSITORY_LOWER=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push image with Jib
        run: |
          mvn -B -ntp -pl ${{ matrix.module }} -am -DskipTests -Dstyle.color=always jib:build